name: continuous integration

on: [push]

jobs:

  client-ci:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install npm dependencies
        run: yarn install --frozen-lockfile --prefer-offline
      - name: Run linter
        run: yarn lint
      - name: Run unit tests
        run: yarn test:unit
      - name: Build Nuxt project
        run: yarn build

  server-ci:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install npm dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint
      - name: Run unit tests
        run: npm run test

  dbms-ci:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dbms

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install npm dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint
      - name: Run unit tests
        run: npm run test
