name: continuous integration

on: [push]

jobs:

  client-ci:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install npm dependencies
        run: |
          cd client
          npm install
      - name: Run linter
        run: |
          cd client
          npm run lint
      - name: Run unit tests
        run: |
          cd client
          npm run test:unit
      - name: Build Nuxt project
        run: |
          cd client
          npm run build

  server-ci:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install npm dependencies
        run: |
          cd server
          npm install
      - name: Run linter
        run: |
          cd server
          npm run lint
      - name: Run unit tests
        run: |
          cd server
          npm run test

  dbms-ci:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install npm dependencies
        run: |
          cd dbms
          npm install
      - name: Run linter
        run: |
          cd dbms
          npm run lint
      - name: Run unit tests
        run: |
          cd dbms
          npm run test
