name: EssaySpring CI/CD

on:
  push:
    branches: [ feature-github-actions ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%s')"
      - name: Build and Push to Docker Hub (Clientside)
        working-directory: ./clientside
        with:
          push: true
          tags: shadrqen/essayspring-client:0.1.${{ steps.date.outputs.date }}
