name: publish dev image docker

on:
  push:
    branches:
    - dev

jobs:

  client-build:

    if: github.repository_owner == 'shadrqen'
    runs-on: ubuntu-latest
    defaults:
      run:
        # Clientside folder working directory.
        working-directory: ./client

    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: | # to build only on changes to the clientside
            client:
              - 'client/**'
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%s')"
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./client
          file: ./client/Dockerfile
          push: true
          tags: ${{ secrets.ES_CLIENT }}:dev

  server-build:

    if: github.repository_owner == 'shadrqen'
    runs-on: ubuntu-latest
    defaults:
      run:
        # Serverside folder working directory.
        working-directory: ./server

    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: | # to build only on changes to the serverside
            server:
              - 'server/**'
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%s')"
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: ${{ secrets.ES_SERVER }}:dev

  dbms-build:

    if: github.repository_owner == 'shadrqen'
    runs-on: ubuntu-latest
    defaults:
      run:
        # DBMS folder working directory.
        working-directory: ./dbms

    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: | # to build only on changes to the dbms
            dbms:
              - 'dbms/**'
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%s')"
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./dbms
          file: ./dbms/Dockerfile
          push: true
          tags: ${{ secrets.ES_DBMS }}:dev
